version: 2
updates: 
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - "sboulema"

- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  assignees:
    - "sboulema"